### ISSUE TITLE
TreeMap#hashCode throws NPE on empty TreeMap

### ISSUE THREAD

**Issue by talios** [functionaljava/functionaljava#187] opened 2015-09-03 12:10 UTC
Whilst porting some code to experimentally use FunctionalJava, I found some failing tests throwing NPEs from this simple line:

    TreeMap.empty(Ord.stringOrd).hashCode();

this throws:

    setUpResources(com.theoryinpractise.halbuilder.ResourceBasicMethodsTest)  Time elapsed: 0.033 sec  <<< FAILURE!
    java.lang.NullPointerException
	at fj.Hash.lambda$anyHash$1182(Hash.java:65)
	at fj.Hash.access$lambda$0(Hash.java)
	at fj.Hash$$Lambda$1.f(Unknown Source)
	at fj.Hash.hash(Hash.java:36)
	at fj.Hash.lambda$p2Hash$1193(Hash.java:297)
	at fj.Hash.access$lambda$9(Hash.java)
	at fj.Hash$$Lambda$10.f(Unknown Source)
	at fj.Hash.hash(Hash.java:36)
	at fj.Hash.lambda$streamHash$1190(Hash.java:233)
	at fj.Hash.access$lambda$6(Hash.java)
	at fj.Hash$$Lambda$7.f(Unknown Source)
	at fj.Hash.hash(Hash.java:36)
	at fj.Hash.lambda$treeMapHash$1192(Hash.java:271)
	at fj.Hash.access$lambda$8(Hash.java)
	at fj.Hash$$Lambda$9.f(Unknown Source)
	at fj.Hash.hash(Hash.java:36)
	at fj.data.TreeMap.hashCode(TreeMap.java:46)
	at com.theoryinpractise.halbuilder.impl.representations.BaseRepresentation.hashCode(BaseRepresentation.java:261)
	at com.theoryinpractise.halbuilder.ResourceBasicMethodsTest.setUpResources(ResourceBasicMethodsTest.java:22)

This is using version 4.4, and seems to occur with any Ord passed in.

**Comment by mperry** [comment] 2015-09-03 22:35
I had a go for version 4.4 and the current master and did not get this issue.  Is it in a branch of your halbuilder repo somewhere (https://github.com/talios/halbuilder) that I can build or run as a test?

**Comment by talios** [comment] 2015-09-04 02:52
Not yet - I just made a standalone project and don't see the issue - interesting.  Will push the changes to the halbuilder repos in a branch soon.

**Comment by mperry** [comment] 2015-09-04 03:06
The TreeMap gets converted to a stream of key value pairs which then gets hashed.  Judging from the stack and the code, it looks like one of the keys or values is null.  However, that doesn't match what you described.  Let me know when you can reproduce the issue.

**Comment by talios** [comment] 2015-09-04 03:23
So TreeMap _allows_ null keys/values? Busy with $work code at the moment but will hopefully look at this again tonight sometime.

**Comment by mperry** [comment] 2015-09-04 03:31
I don't know, although I would guess not.  I thought there might be a null by looking at your stack trace and the code.

**Comment by tonymorris** [comment] 2015-09-04 03:42
Functional Java generally assumes that `null` does not exist, since it is not useful. If it happens that `null` is used, the behaviour is simply, "you accept all responsibility for imminent consequences [ps: you are not going to have a nice day today]".

However, the code above should not use `null` at all and so if it causes NPE, then there is a bug.

**Comment by talios** [comment] 2015-09-04 03:58
Just quickly reran my code and looking in the debugger I see I indeed, I do have `Set((testprop,Some(value)),(nullprop,Some(null)))` - if allowing nulls as keys/values is correct, then hashCode() should respect that.

I kinda prefer how Guava's ImmutableMap etc. fast fail and blow up if you try add nulls.

So, looks like I have something broken in my test data, but also something `TreeMap` may not blow up on?

**Comment by mperry** [comment] 2015-09-04 04:00
Other than Option, I think sometimes when generating quickcheck style values you want to use nulls.

**Comment by talios** [comment] 2015-09-04 04:04
Yep - thinking of the usage in my library, I also want to track that "yes, the user explicitly set this value to null, rather than didn't set it" so that when I eventually serialize to JSON I can emit `{"name": null}`.

**Comment by tonymorris** [comment] 2015-09-04 04:33
Consider what it really means to "fail fast when using a `null` value." When to fail? At each method call? Then we must check for `null` for every function argument ever written. Should this go all the way up beyond Functional Java? What about local values; should they be checked too?

Fact is, no library fails fast for `null` because it is intractable, not to mention the catastrophic performance implication. It is better to simply assume responsible programming. Don't use `null` unless you actually want to have a bad day; it has a total of zero use-cases. It's no different to all the other self-harming activities that are always conveniently available, yet we don't give those a second thought; doing so would bog us down.

"I might put a check in place to ensure I don't jump in front of that bus." Just don't jump in front of the bus. Better, don't even think about the bus.

**Comment by talios** [comment] 2015-09-04 04:46
Fair enough - so how should one model an absent value in a TreeMap then?  I could `TreeMap<String,Option<Object>>`, which is probably correct.

It was just surprising since standard java `Map`'s handle null's when calculating hashCode ( however, one should expect the same results from something that's not the same ).

**Comment by tonymorris** [comment] 2015-09-04 04:50
If the mapping might exist but map to "not a value", then yeah use `Option`. Using `Object` should be avoided however. Do you want a sum type instead?

**Comment by talios** [comment] 2015-09-04 04:56
In this scenario, the object may ( not always ) be deserialised/parsed from JSON, so could be a value, a list, a map, a null ( as parsed via Jackson currently ), and optionally further proxied into a `.class` instance. How that is modelled may change depending on if I stick with FJ and/or how the library reshapes itself.

**Comment by tonymorris** [comment] 2015-09-04 04:57
You should create a sum type to model this accordingly. There are tricks in Java to do this. The `Either` type is a general example.

**Comment by mperry** [comment] 2015-09-08 07:29
@talios I am going to close this issue.  Let me know if we need to reopen it.

**Closed by mperry** 2015-09-08 07:29 UTC
